spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/jpashop?allowPublicKeyRetrieval=true&useUnicode=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1111   # password 없으면 주석 처리
  jpa:
    hibernate:
      ddl-auto: none  # 초기 한번만 create 로 하고 none 으로 변경할 것
    properties:
      hibernate:
        show-sql: true
        format_sql: true

# session : expire  60, 180 ,...
server:
  servlet:
    session:
      timeout: 60
      tracking-modes:  cookie

